In [31]:
import matplotlib.pyplot as plt
import scipy
import numpy as np
import core2
from importlib import reload

In [57]:
mat = scipy.io.loadmat('icepack2.mat')
globals().update(mat)
prior_aicen = mat['prior_aicen']
prior_vicen = mat['prior_vicen']
true_aicen = mat['true_aicen']
z_prior = mat['z_prior']
z_posterior = mat['z_posterior']

h_bnd = [0,
         0.64450721681942580,
         1.3914334975763036,
         2.4701793819598885,
         4.5672879188504911,
         9.3338418158681744]
h_bnd = np.array(h_bnd)

In [58]:
a_samples, v_samples = prior_aicen[:,:,1].T, prior_vicen[:,:,1].T

In [59]:
v_samples / a_samples

/tmp/ipykernel_14980/841743095.py:1: RuntimeWarning: invalid value encountered in divide
  v_samples / a_samples


array([[       nan, 0.97467632, 1.39754768, 2.48929089, 4.59565008],
       [       nan, 0.98239126, 1.39839562, 2.49031153, 4.59736621],
       [0.15490887, 0.98528435, 1.44768819, 4.30342152, 4.56732488],
       [       nan, 1.00633751, 1.92946861, 2.47829955, 4.6700834 ],
       [       nan, 0.96285753, 1.39682608, 2.85250406,        nan],
       [       nan, 1.05215811, 1.3987495 , 2.48475742,        nan],
       [       nan, 0.99402617, 1.39739674, 3.78352468, 4.57376984],
       [       nan, 1.00298448, 1.39764178, 3.88442904, 4.57372701],
       [       nan, 0.97972074, 1.39699215, 3.46105939, 4.57271058],
       [       nan, 1.02731383, 1.39953151, 2.48609416, 7.17309884],
       [       nan, 1.00273038, 1.39937542, 2.4865215 , 7.72440022],
       [       nan, 1.04029348, 1.40025447, 2.48760175, 4.64074294],
       [0.14825427, 0.96689042, 1.50202548, 2.49023041, 4.6325787 ],
       [0.15082377, 0.98627249, 1.50849342, 2.49240825, 4.56802255],
       [       nan, 0.978655  , 1.

In [78]:
reload(core2)

<module 'core2' from '/home/oscar/grooms/core2.py'>

In [79]:
se = core2.SampleEnsemble(a_samples, v_samples, h_bnd)

In [80]:
se.l


array([[0.00000000e+00, 5.47116636e-01, 9.94489050e-03, 1.69885108e-03,
        6.04862265e-03],
       [0.00000000e+00, 5.32578146e-01, 1.22938622e-02, 2.60436111e-03,
        1.09564921e-02],
       [9.63140513e-04, 3.00676837e-01, 4.09693566e-01, 1.46187145e-03,
        2.16977578e-06],
       [0.00000000e+00, 4.76290405e-01, 3.29712379e-02, 1.18120705e-03,
        7.25002861e-03],
       [0.00000000e+00, 5.68585103e-01, 7.47864580e-03, 3.15988347e-05,
        0.00000000e+00],
       [0.00000000e+00, 4.38383032e-01, 2.36782209e-02, 9.64895387e-03,
        0.00000000e+00],
       [0.00000000e+00, 5.22316217e-01, 1.21802166e-02, 1.64700761e-03,
        4.78587162e-05],
       [0.00000000e+00, 5.10334799e-01, 1.38649019e-02, 1.07148755e-03,
        4.14029023e-05],
       [0.00000000e+00, 5.44662146e-01, 9.72232144e-03, 3.25682346e-04,
        2.64085012e-06],
       [0.00000000e+00, 4.75005747e-01, 2.20827477e-02, 6.01086736e-04,
        6.04167885e-04],
       [0.00000000e+00, 4.9979

In [82]:
se.x

array([[1.63821209e-03, 0.00000000e+00, 5.47116636e-01, 9.94489050e-03,
        1.69885108e-03, 6.04862265e-03, 0.00000000e+00, 4.33444270e-01,
        5.66875187e-05, 1.56244732e-05, 3.62062136e-05],
       [1.46318893e-03, 0.00000000e+00, 5.32578146e-01, 1.22938622e-02,
        2.60436111e-03, 1.09564921e-02, 0.00000000e+00, 4.39929269e-01,
        7.98588136e-05, 2.52440937e-05, 6.95775980e-05],
       [1.91973643e-03, 9.63140513e-04, 3.00676837e-01, 4.09693566e-01,
        1.46187145e-03, 2.16977578e-06, 3.04737576e-04, 2.52281193e-01,
        2.25402289e-02, 1.01565199e-02, 1.68235949e-11],
       [1.81948132e-03, 0.00000000e+00, 4.76290405e-01, 3.29712379e-02,
        1.18120705e-03, 7.25002861e-03, 0.00000000e+00, 4.47515165e-01,
        3.28080827e-02, 4.59150480e-06, 1.59800334e-04],
       [1.50960566e-03, 0.00000000e+00, 5.68585103e-01, 7.47864580e-03,
        3.15988347e-05, 0.00000000e+00, 0.00000000e+00, 4.22350428e-01,
        3.75730703e-05, 7.04521120e-06, 0.00000000e+

In [84]:
se.x









array([[1.63821209e-03, 0.00000000e+00, 5.47116636e-01, 9.94489050e-03,
        1.69885108e-03, 6.04862265e-03, 0.00000000e+00, 4.33444270e-01,
        5.66875187e-05, 1.56244732e-05, 3.62062136e-05],
       [1.46318893e-03, 0.00000000e+00, 5.32578146e-01, 1.22938622e-02,
        2.60436111e-03, 1.09564921e-02, 0.00000000e+00, 4.39929269e-01,
        7.98588136e-05, 2.52440937e-05, 6.95775980e-05],
       [1.91973643e-03, 9.63140513e-04, 3.00676837e-01, 4.09693566e-01,
        1.46187145e-03, 2.16977578e-06, 3.04737576e-04, 2.52281193e-01,
        2.25402289e-02, 1.01565199e-02, 1.68235949e-11],
       [1.81948132e-03, 0.00000000e+00, 4.76290405e-01, 3.29712379e-02,
        1.18120705e-03, 7.25002861e-03, 0.00000000e+00, 4.47515165e-01,
        3.28080827e-02, 4.59150480e-06, 1.59800334e-04],
       [1.50960566e-03, 0.00000000e+00, 5.68585103e-01, 7.47864580e-03,
        3.15988347e-05, 0.00000000e+00, 0.00000000e+00, 4.22350428e-01,
        3.75730703e-05, 7.04521120e-06, 0.00000000e+